##
## .condor file for matlab simulation
##
####################
#
# Usuario y grupo de investigacion
User = dbetran
Grupo = tfd

# Para Matlab siempre vanilla
Universe = vanilla


# Cambiar este valor para que coincida con el directorio
# en el que se encuentran los ficheros de condor. Se recomienda
# el crear un directorio para cada calculo
InputDir = /home/$(Grupo)/$(User)/DropletEvaporation

#
# Cambiar para indicar el directorio en el que se
# desea la salida. Se recomienda que sea un directorio
# particular para Condor_Matlab (se generan mucho ficheros)
OutputDir = /home/$(Grupo)/$(User)/DropletEvaporation

# The absolute path (not relative to InitialDir!) to
# your Executable

# matlab.sh es un wrapper que llama a Matlab en cada nodo

Executable = $(InputDir)/matlab.sh
InitialDir = $(InputDir)
Error = $(OutputDir)/err
Log = $(OutputDir)/log

# This is to be turned on for Matlab simulations.
GetEnv = true

# estas variables son para pasarlas como argumentos a nuestra función
# Si nuestro codigo en Matlab tiene parametros, deben indicarse en este paso
Arguments = Run_droplet_test_Cluster($(Process)+1); exit;

# Salida standard del programa
Output = $(OutputDir)/output-$(Process).txt

# Reservamos memoria RAM del nodo (en Mb)
# IMPORTANTE!!! : Si no estimamos la memoria corremos el
# riesgo de que Condor mate nuestro calculo
request_memory = 8*1024
request_cpus = 1
+Architecture="UNDEFINED" 

Queue 1
